Repository dnd-side-project/dnd-10th-10-iOS, pull requests merged in 2024-02, with the labels that each got.

#20 [Feat] 방 입장 대기 뷰 UI 구성
  Basterdz-iOS/Basterdz-iOS.xcodeproj/project.pbxproj
  Basterdz-iOS/Basterdz-iOS/Presentation/Room/View/CreateRoom/EnterRoomNameView.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Room/View/WaitingRoomView.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Room/ViewModel/CreateRoom/EnterRoomNameViewModel.swift
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_blue.imageset/Contents.json
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_blue.imageset/profile_blue.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_blue.imageset/profile_blue@2x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_blue.imageset/profile_blue@3x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_enabled.imageset/Contents.json
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_enabled.imageset/profile_enabled.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_enabled.imageset/profile_enabled@2x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_enabled.imageset/profile_enabled@3x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_green.imageset/Contents.json
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_green.imageset/profile_green.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_green.imageset/profile_green@2x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_green.imageset/profile_green@3x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_pink.imageset/Contents.json
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_pink.imageset/profile_pink.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_pink.imageset/profile_pink@2x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_pink.imageset/profile_pink@3x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_purple.imageset/Contents.json
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_purple.imageset/profile_purple.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_purple.imageset/profile_purple@2x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_purple.imageset/profile_purple@3x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_red.imageset/Contents.json
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_red.imageset/profile_red.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_red.imageset/profile_red@2x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_red.imageset/profile_red@3x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_yellow.imageset/Contents.json
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_yellow.imageset/profile_yellow.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_yellow.imageset/profile_yellow@2x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/profile_yellow.imageset/profile_yellow@3x.png
  Basterdz-iOS/Basterdz-iOS/Util/Constant/BasterdzImage.swift
  Basterdz-iOS/Basterdz-iOS/Util/Constant/BasterdzInt.swift
Labels: 📱UI

#23 [Feat] 초대인원 미달 팝업 뷰 UI 구성
  Basterdz-iOS/Basterdz-iOS.xcodeproj/project.pbxproj
  Basterdz-iOS/Basterdz-iOS/Presentation/Room/View/PopUp/BeforeStartView.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Room/View/PopUp/EnterConfirmView.swift
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/redBomb.imageset/Contents.json
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/redBomb.imageset/redBomb.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/redBomb.imageset/redBomb@2x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/redBomb.imageset/redBomb@3x.png
  Basterdz-iOS/Basterdz-iOS/Util/Constant/BasterdzImage.swift
Labels: 📱UI

#27 [Config] 네트워크 레이어 세팅
  Basterdz-iOS/Basterdz-iOS.xcodeproj/project.pbxproj
  Basterdz-iOS/Basterdz-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Basterdz-iOS/Basterdz-iOS/Data/Network/.gitkeep
  Basterdz-iOS/Basterdz-iOS/Data/Network/APIs/RoomAPI.swift
  Basterdz-iOS/Basterdz-iOS/Infrastructure/Network/Foundation/APIService.swift
  Basterdz-iOS/Basterdz-iOS/Infrastructure/Network/Foundation/BaseAPI.swift
  Basterdz-iOS/Basterdz-iOS/Infrastructure/Network/Foundation/NetworkEnvironment.swift
  Basterdz-iOS/Basterdz-iOS/Infrastructure/Network/Foundation/NetworkError.swift
  Basterdz-iOS/Basterdz-iOS/Infrastructure/Network/Foundation/NetworkProvider.swift
  Basterdz-iOS/Basterdz-iOS/Infrastructure/Network/Model/CommonResponse.swift
  Basterdz-iOS/Basterdz-iOS/Infrastructure/Network/Model/ErrorResponse.swift
  Basterdz-iOS/Basterdz-iOS/Infrastructure/Network/network.swift
Labels: ⚙️Setting, 📡 Network

#29 [Feat] 초대코드 입력 뷰 기능 구현
  Basterdz-iOS/Basterdz-iOS.xcodeproj/project.pbxproj
  Basterdz-iOS/Basterdz-iOS/DesignSystem/Component/BasterdzPopUpView.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Room/Coordinator/RoomCoordinator.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Room/View/EnterInviteCodeView.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Room/View/PopUp/EnterConfirmView.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Room/ViewModel/CreateRoom/EnterInviteCodeViewModel.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Room/ViewModel/EnterInviteCodeViewModel.swift
Labels: ✨ Feature

#30 [Feat] 부스터 메인 View 구현
  Basterdz-iOS/Basterdz-iOS/Presentation/Booster/View/BoosterView.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Booster/ViewModel/BoosterViewModel.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Home/View/HomeView.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/MyPage/View/MyPageView.swift
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Icon/alarm.imageset/Contents.json
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Icon/alarm.imageset/alarm.svg
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/fire.imageset/Contents.json
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/fire.imageset/boosterFire.svg
  Basterdz-iOS/Basterdz-iOS/Util/Constant/BasterdzImage.swift
Labels: 📱UI

#34 [Feat] 스플래시 뷰 UI 구성
  Basterdz-iOS/Basterdz-iOS.xcodeproj/project.pbxproj
  Basterdz-iOS/Basterdz-iOS/Application/Basterdz_iOSApp.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Common/SplashView.swift
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/basterdzIcon.imageset/Contents.json
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/basterdzIcon.imageset/basterdzIcon.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/basterdzIcon.imageset/basterdzIcon@2x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/basterdzIcon.imageset/basterdzIcon@3x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/basterdz_white.imageset/Contents.json
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/basterdz_white.imageset/basterdz_white.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/basterdz_white.imageset/basterdz_white@2x.png
  Basterdz-iOS/Basterdz-iOS/Resource/Image/Assets.xcassets/Image/basterdz_white.imageset/basterdz_white@3x.png
  Basterdz-iOS/Basterdz-iOS/Util/Constant/BasterdzImage.swift
Labels: 📱UI, ✨ Feature

#41 [Config] FCM 세팅
  Basterdz-iOS/Basterdz-iOS.xcodeproj/project.pbxproj
  Basterdz-iOS/Basterdz-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Basterdz-iOS/Basterdz-iOS/Application/AppDelegate.swift
  Basterdz-iOS/Basterdz-iOS/Application/Basterdz_iOSApp.swift
  Basterdz-iOS/Basterdz-iOS/Basterdz-iOS.entitlements
  Basterdz-iOS/Basterdz-iOS/Presentation/Tab/TabView.swift
  Basterdz-iOS/Basterdz-iOS/Support/Info.plist
Labels: ⚙️Setting

#42 [Feat] 방 디테일 domain 구현
  Basterdz-iOS/Basterdz-iOS.xcodeproj/project.pbxproj
  Basterdz-iOS/Basterdz-iOS/Data/Network/APIs/RoomAPI.swift
  Basterdz-iOS/Basterdz-iOS/Data/Network/APIs/RoomAPIService.swift
  Basterdz-iOS/Basterdz-iOS/Data/Network/Model/GetProgressRoomDTO.swift
  Basterdz-iOS/Basterdz-iOS/Data/Network/Model/RankDTO.swift
  Basterdz-iOS/Basterdz-iOS/Data/Network/Model/ScreenTimeDTO.swift
  Basterdz-iOS/Basterdz-iOS/DesignSystem/Component/BasterdzProgressBar.swift
  Basterdz-iOS/Basterdz-iOS/Domain/Entities/ChallengerEntity.swift
  Basterdz-iOS/Basterdz-iOS/Domain/Entities/RoomEntity.swift
  Basterdz-iOS/Basterdz-iOS/Domain/Interfaces/RoomNetworkable.swift
  Basterdz-iOS/Basterdz-iOS/Domain/UseCases/GetProgressRoomInfoUseCase.swift
  Basterdz-iOS/Basterdz-iOS/Domain/UseCases/GetRankUseCase.swift
  Basterdz-iOS/Basterdz-iOS/Domain/UseCases/GetRoomScreenTimeUseCase.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Booster/ViewModel/BoosterViewModel.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Home/Coordinator/HomeCoordinator.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Home/View/HomeView.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Room/View/ChallengeRoomView.swift
  Basterdz-iOS/Basterdz-iOS/Presentation/Room/ViewModel/ChallengeRoomViewModel.swift
Labels: 📡 Network, ✨ Feature
